const BOOKING_ERROR_CODES = {
  BOOKING_BID_NOT_FOUND: "BOOKING_BID_NOT_FOUND",
  BOOKING_LOAD_NOT_FOUND: "BOOKING_LOAD_NOT_FOUND",
  BOOKING_FORBIDDEN: "BOOKING_FORBIDDEN",
  BOOKING_BID_EXPIRED: "BOOKING_BID_EXPIRED",
  BOOKING_LOAD_CONFLICT: "BOOKING_LOAD_CONFLICT",
  BOOKING_INVALID_STATE: "BOOKING_INVALID_STATE",
  BOOKING_NO_SUGGESTION: "BOOKING_NO_SUGGESTION",
  BOOKING_INTEGRITY: "BOOKING_INTEGRITY",
  BOOKING_TRUCK_PROFILE: "BOOKING_TRUCK_PROFILE",
  BOOKING_INTERNAL: "BOOKING_INTERNAL",
  BOOKING_IDEMPOTENCY_KEY_INVALID: "BOOKING_IDEMPOTENCY_KEY_INVALID",
  BOOKING_VALIDATION_FAILED: "BOOKING_VALIDATION_FAILED"
};

class BookingError extends Error {
  constructor(code, statusCode, message) {
    super(message);
    this.name = "BookingError";
    this.code = code;
    this.statusCode = statusCode;
  }
}

module.exports = {
  BookingError,
  BOOKING_ERROR_CODES
};
